FROM python:slim

LABEL maintainer="Joe Block <jpb@unixorn.net>"
LABEL description="Test image for ha-mqtt-discoverable module"

RUN mkdir /data && \
  mkdir /config && \
  pip install --upgrade pip

# Keep from having to reinstall all the dependencies every time we
# rebuild during tests
COPY requirements.txt /data
RUN pip install --no-cache-dir -r /data/requirements.txt

COPY dist/*.whl /data
RUN pip install --no-cache-dir /data/*.whl

USER nobody

CMD ["bash", "-l"]
